// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: quick_play.proto

#ifndef PROTOBUF_quick_5fplay_2eproto__INCLUDED
#define PROTOBUF_quick_5fplay_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_quick_5fplay_2eproto();
void protobuf_AssignDesc_quick_5fplay_2eproto();
void protobuf_ShutdownFile_quick_5fplay_2eproto();

class BINQuickPlayRequest;
class BINQuickPlayResponse;

// ===================================================================

class BINQuickPlayRequest : public ::google::protobuf::Message {
 public:
  BINQuickPlayRequest();
  virtual ~BINQuickPlayRequest();

  BINQuickPlayRequest(const BINQuickPlayRequest& from);

  inline BINQuickPlayRequest& operator=(const BINQuickPlayRequest& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const BINQuickPlayRequest& default_instance();

  void Swap(BINQuickPlayRequest* other);

  // implements Message ----------------------------------------------

  BINQuickPlayRequest* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const BINQuickPlayRequest& from);
  void MergeFrom(const BINQuickPlayRequest& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string deviceId = 1;
  inline bool has_deviceid() const;
  inline void clear_deviceid();
  static const int kDeviceIdFieldNumber = 1;
  inline const ::std::string& deviceid() const;
  inline void set_deviceid(const ::std::string& value);
  inline void set_deviceid(const char* value);
  inline void set_deviceid(const char* value, size_t size);
  inline ::std::string* mutable_deviceid();
  inline ::std::string* release_deviceid();
  inline void set_allocated_deviceid(::std::string* deviceid);

  // optional string deviceInfo = 2;
  inline bool has_deviceinfo() const;
  inline void clear_deviceinfo();
  static const int kDeviceInfoFieldNumber = 2;
  inline const ::std::string& deviceinfo() const;
  inline void set_deviceinfo(const ::std::string& value);
  inline void set_deviceinfo(const char* value);
  inline void set_deviceinfo(const char* value, size_t size);
  inline ::std::string* mutable_deviceinfo();
  inline ::std::string* release_deviceinfo();
  inline void set_allocated_deviceinfo(::std::string* deviceinfo);

  // @@protoc_insertion_point(class_scope:BINQuickPlayRequest)
 private:
  inline void set_has_deviceid();
  inline void clear_has_deviceid();
  inline void set_has_deviceinfo();
  inline void clear_has_deviceinfo();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::std::string* deviceid_;
  ::std::string* deviceinfo_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_quick_5fplay_2eproto();
  friend void protobuf_AssignDesc_quick_5fplay_2eproto();
  friend void protobuf_ShutdownFile_quick_5fplay_2eproto();

  void InitAsDefaultInstance();
  static BINQuickPlayRequest* default_instance_;
};
// -------------------------------------------------------------------

class BINQuickPlayResponse : public ::google::protobuf::Message {
 public:
  BINQuickPlayResponse();
  virtual ~BINQuickPlayResponse();

  BINQuickPlayResponse(const BINQuickPlayResponse& from);

  inline BINQuickPlayResponse& operator=(const BINQuickPlayResponse& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const BINQuickPlayResponse& default_instance();

  void Swap(BINQuickPlayResponse* other);

  // implements Message ----------------------------------------------

  BINQuickPlayResponse* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const BINQuickPlayResponse& from);
  void MergeFrom(const BINQuickPlayResponse& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required bool responseCode = 1;
  inline bool has_responsecode() const;
  inline void clear_responsecode();
  static const int kResponseCodeFieldNumber = 1;
  inline bool responsecode() const;
  inline void set_responsecode(bool value);

  // optional string message = 2;
  inline bool has_message() const;
  inline void clear_message();
  static const int kMessageFieldNumber = 2;
  inline const ::std::string& message() const;
  inline void set_message(const ::std::string& value);
  inline void set_message(const char* value);
  inline void set_message(const char* value, size_t size);
  inline ::std::string* mutable_message();
  inline ::std::string* release_message();
  inline void set_allocated_message(::std::string* message);

  // optional int64 userId = 3;
  inline bool has_userid() const;
  inline void clear_userid();
  static const int kUserIdFieldNumber = 3;
  inline ::google::protobuf::int64 userid() const;
  inline void set_userid(::google::protobuf::int64 value);

  // optional string userName = 4;
  inline bool has_username() const;
  inline void clear_username();
  static const int kUserNameFieldNumber = 4;
  inline const ::std::string& username() const;
  inline void set_username(const ::std::string& value);
  inline void set_username(const char* value);
  inline void set_username(const char* value, size_t size);
  inline ::std::string* mutable_username();
  inline ::std::string* release_username();
  inline void set_allocated_username(::std::string* username);

  // optional int64 cash = 5;
  inline bool has_cash() const;
  inline void clear_cash();
  static const int kCashFieldNumber = 5;
  inline ::google::protobuf::int64 cash() const;
  inline void set_cash(::google::protobuf::int64 value);

  // optional int64 gold = 6;
  inline bool has_gold() const;
  inline void clear_gold();
  static const int kGoldFieldNumber = 6;
  inline ::google::protobuf::int64 gold() const;
  inline void set_gold(::google::protobuf::int64 value);

  // optional int32 avatarId = 7;
  inline bool has_avatarid() const;
  inline void clear_avatarid();
  static const int kAvatarIdFieldNumber = 7;
  inline ::google::protobuf::int32 avatarid() const;
  inline void set_avatarid(::google::protobuf::int32 value);

  // optional string avatarPath = 8;
  inline bool has_avatarpath() const;
  inline void clear_avatarpath();
  static const int kAvatarPathFieldNumber = 8;
  inline const ::std::string& avatarpath() const;
  inline void set_avatarpath(const ::std::string& value);
  inline void set_avatarpath(const char* value);
  inline void set_avatarpath(const char* value, size_t size);
  inline ::std::string* mutable_avatarpath();
  inline ::std::string* release_avatarpath();
  inline void set_allocated_avatarpath(::std::string* avatarpath);

  // optional int32 level = 9;
  inline bool has_level() const;
  inline void clear_level();
  static const int kLevelFieldNumber = 9;
  inline ::google::protobuf::int32 level() const;
  inline void set_level(::google::protobuf::int32 value);

  // optional int64 exp = 10;
  inline bool has_exp() const;
  inline void clear_exp();
  static const int kExpFieldNumber = 10;
  inline ::google::protobuf::int64 exp() const;
  inline void set_exp(::google::protobuf::int64 value);

  // optional string sessionId = 11;
  inline bool has_sessionid() const;
  inline void clear_sessionid();
  static const int kSessionIdFieldNumber = 11;
  inline const ::std::string& sessionid() const;
  inline void set_sessionid(const ::std::string& value);
  inline void set_sessionid(const char* value);
  inline void set_sessionid(const char* value, size_t size);
  inline ::std::string* mutable_sessionid();
  inline ::std::string* release_sessionid();
  inline void set_allocated_sessionid(::std::string* sessionid);

  // optional bool enableDebugLag = 12;
  inline bool has_enabledebuglag() const;
  inline void clear_enabledebuglag();
  static const int kEnableDebugLagFieldNumber = 12;
  inline bool enabledebuglag() const;
  inline void set_enabledebuglag(bool value);

  // @@protoc_insertion_point(class_scope:BINQuickPlayResponse)
 private:
  inline void set_has_responsecode();
  inline void clear_has_responsecode();
  inline void set_has_message();
  inline void clear_has_message();
  inline void set_has_userid();
  inline void clear_has_userid();
  inline void set_has_username();
  inline void clear_has_username();
  inline void set_has_cash();
  inline void clear_has_cash();
  inline void set_has_gold();
  inline void clear_has_gold();
  inline void set_has_avatarid();
  inline void clear_has_avatarid();
  inline void set_has_avatarpath();
  inline void clear_has_avatarpath();
  inline void set_has_level();
  inline void clear_has_level();
  inline void set_has_exp();
  inline void clear_has_exp();
  inline void set_has_sessionid();
  inline void clear_has_sessionid();
  inline void set_has_enabledebuglag();
  inline void clear_has_enabledebuglag();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::std::string* message_;
  ::google::protobuf::int64 userid_;
  ::std::string* username_;
  ::google::protobuf::int64 cash_;
  ::google::protobuf::int64 gold_;
  bool responsecode_;
  bool enabledebuglag_;
  ::google::protobuf::int32 avatarid_;
  ::std::string* avatarpath_;
  ::google::protobuf::int64 exp_;
  ::std::string* sessionid_;
  ::google::protobuf::int32 level_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(12 + 31) / 32];

  friend void  protobuf_AddDesc_quick_5fplay_2eproto();
  friend void protobuf_AssignDesc_quick_5fplay_2eproto();
  friend void protobuf_ShutdownFile_quick_5fplay_2eproto();

  void InitAsDefaultInstance();
  static BINQuickPlayResponse* default_instance_;
};
// ===================================================================


// ===================================================================

// BINQuickPlayRequest

// required string deviceId = 1;
inline bool BINQuickPlayRequest::has_deviceid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void BINQuickPlayRequest::set_has_deviceid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void BINQuickPlayRequest::clear_has_deviceid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void BINQuickPlayRequest::clear_deviceid() {
  if (deviceid_ != &::google::protobuf::internal::kEmptyString) {
    deviceid_->clear();
  }
  clear_has_deviceid();
}
inline const ::std::string& BINQuickPlayRequest::deviceid() const {
  return *deviceid_;
}
inline void BINQuickPlayRequest::set_deviceid(const ::std::string& value) {
  set_has_deviceid();
  if (deviceid_ == &::google::protobuf::internal::kEmptyString) {
    deviceid_ = new ::std::string;
  }
  deviceid_->assign(value);
}
inline void BINQuickPlayRequest::set_deviceid(const char* value) {
  set_has_deviceid();
  if (deviceid_ == &::google::protobuf::internal::kEmptyString) {
    deviceid_ = new ::std::string;
  }
  deviceid_->assign(value);
}
inline void BINQuickPlayRequest::set_deviceid(const char* value, size_t size) {
  set_has_deviceid();
  if (deviceid_ == &::google::protobuf::internal::kEmptyString) {
    deviceid_ = new ::std::string;
  }
  deviceid_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* BINQuickPlayRequest::mutable_deviceid() {
  set_has_deviceid();
  if (deviceid_ == &::google::protobuf::internal::kEmptyString) {
    deviceid_ = new ::std::string;
  }
  return deviceid_;
}
inline ::std::string* BINQuickPlayRequest::release_deviceid() {
  clear_has_deviceid();
  if (deviceid_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = deviceid_;
    deviceid_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void BINQuickPlayRequest::set_allocated_deviceid(::std::string* deviceid) {
  if (deviceid_ != &::google::protobuf::internal::kEmptyString) {
    delete deviceid_;
  }
  if (deviceid) {
    set_has_deviceid();
    deviceid_ = deviceid;
  } else {
    clear_has_deviceid();
    deviceid_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// optional string deviceInfo = 2;
inline bool BINQuickPlayRequest::has_deviceinfo() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void BINQuickPlayRequest::set_has_deviceinfo() {
  _has_bits_[0] |= 0x00000002u;
}
inline void BINQuickPlayRequest::clear_has_deviceinfo() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void BINQuickPlayRequest::clear_deviceinfo() {
  if (deviceinfo_ != &::google::protobuf::internal::kEmptyString) {
    deviceinfo_->clear();
  }
  clear_has_deviceinfo();
}
inline const ::std::string& BINQuickPlayRequest::deviceinfo() const {
  return *deviceinfo_;
}
inline void BINQuickPlayRequest::set_deviceinfo(const ::std::string& value) {
  set_has_deviceinfo();
  if (deviceinfo_ == &::google::protobuf::internal::kEmptyString) {
    deviceinfo_ = new ::std::string;
  }
  deviceinfo_->assign(value);
}
inline void BINQuickPlayRequest::set_deviceinfo(const char* value) {
  set_has_deviceinfo();
  if (deviceinfo_ == &::google::protobuf::internal::kEmptyString) {
    deviceinfo_ = new ::std::string;
  }
  deviceinfo_->assign(value);
}
inline void BINQuickPlayRequest::set_deviceinfo(const char* value, size_t size) {
  set_has_deviceinfo();
  if (deviceinfo_ == &::google::protobuf::internal::kEmptyString) {
    deviceinfo_ = new ::std::string;
  }
  deviceinfo_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* BINQuickPlayRequest::mutable_deviceinfo() {
  set_has_deviceinfo();
  if (deviceinfo_ == &::google::protobuf::internal::kEmptyString) {
    deviceinfo_ = new ::std::string;
  }
  return deviceinfo_;
}
inline ::std::string* BINQuickPlayRequest::release_deviceinfo() {
  clear_has_deviceinfo();
  if (deviceinfo_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = deviceinfo_;
    deviceinfo_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void BINQuickPlayRequest::set_allocated_deviceinfo(::std::string* deviceinfo) {
  if (deviceinfo_ != &::google::protobuf::internal::kEmptyString) {
    delete deviceinfo_;
  }
  if (deviceinfo) {
    set_has_deviceinfo();
    deviceinfo_ = deviceinfo;
  } else {
    clear_has_deviceinfo();
    deviceinfo_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// -------------------------------------------------------------------

// BINQuickPlayResponse

// required bool responseCode = 1;
inline bool BINQuickPlayResponse::has_responsecode() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void BINQuickPlayResponse::set_has_responsecode() {
  _has_bits_[0] |= 0x00000001u;
}
inline void BINQuickPlayResponse::clear_has_responsecode() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void BINQuickPlayResponse::clear_responsecode() {
  responsecode_ = false;
  clear_has_responsecode();
}
inline bool BINQuickPlayResponse::responsecode() const {
  return responsecode_;
}
inline void BINQuickPlayResponse::set_responsecode(bool value) {
  set_has_responsecode();
  responsecode_ = value;
}

// optional string message = 2;
inline bool BINQuickPlayResponse::has_message() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void BINQuickPlayResponse::set_has_message() {
  _has_bits_[0] |= 0x00000002u;
}
inline void BINQuickPlayResponse::clear_has_message() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void BINQuickPlayResponse::clear_message() {
  if (message_ != &::google::protobuf::internal::kEmptyString) {
    message_->clear();
  }
  clear_has_message();
}
inline const ::std::string& BINQuickPlayResponse::message() const {
  return *message_;
}
inline void BINQuickPlayResponse::set_message(const ::std::string& value) {
  set_has_message();
  if (message_ == &::google::protobuf::internal::kEmptyString) {
    message_ = new ::std::string;
  }
  message_->assign(value);
}
inline void BINQuickPlayResponse::set_message(const char* value) {
  set_has_message();
  if (message_ == &::google::protobuf::internal::kEmptyString) {
    message_ = new ::std::string;
  }
  message_->assign(value);
}
inline void BINQuickPlayResponse::set_message(const char* value, size_t size) {
  set_has_message();
  if (message_ == &::google::protobuf::internal::kEmptyString) {
    message_ = new ::std::string;
  }
  message_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* BINQuickPlayResponse::mutable_message() {
  set_has_message();
  if (message_ == &::google::protobuf::internal::kEmptyString) {
    message_ = new ::std::string;
  }
  return message_;
}
inline ::std::string* BINQuickPlayResponse::release_message() {
  clear_has_message();
  if (message_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = message_;
    message_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void BINQuickPlayResponse::set_allocated_message(::std::string* message) {
  if (message_ != &::google::protobuf::internal::kEmptyString) {
    delete message_;
  }
  if (message) {
    set_has_message();
    message_ = message;
  } else {
    clear_has_message();
    message_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// optional int64 userId = 3;
inline bool BINQuickPlayResponse::has_userid() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void BINQuickPlayResponse::set_has_userid() {
  _has_bits_[0] |= 0x00000004u;
}
inline void BINQuickPlayResponse::clear_has_userid() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void BINQuickPlayResponse::clear_userid() {
  userid_ = GOOGLE_LONGLONG(0);
  clear_has_userid();
}
inline ::google::protobuf::int64 BINQuickPlayResponse::userid() const {
  return userid_;
}
inline void BINQuickPlayResponse::set_userid(::google::protobuf::int64 value) {
  set_has_userid();
  userid_ = value;
}

// optional string userName = 4;
inline bool BINQuickPlayResponse::has_username() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void BINQuickPlayResponse::set_has_username() {
  _has_bits_[0] |= 0x00000008u;
}
inline void BINQuickPlayResponse::clear_has_username() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void BINQuickPlayResponse::clear_username() {
  if (username_ != &::google::protobuf::internal::kEmptyString) {
    username_->clear();
  }
  clear_has_username();
}
inline const ::std::string& BINQuickPlayResponse::username() const {
  return *username_;
}
inline void BINQuickPlayResponse::set_username(const ::std::string& value) {
  set_has_username();
  if (username_ == &::google::protobuf::internal::kEmptyString) {
    username_ = new ::std::string;
  }
  username_->assign(value);
}
inline void BINQuickPlayResponse::set_username(const char* value) {
  set_has_username();
  if (username_ == &::google::protobuf::internal::kEmptyString) {
    username_ = new ::std::string;
  }
  username_->assign(value);
}
inline void BINQuickPlayResponse::set_username(const char* value, size_t size) {
  set_has_username();
  if (username_ == &::google::protobuf::internal::kEmptyString) {
    username_ = new ::std::string;
  }
  username_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* BINQuickPlayResponse::mutable_username() {
  set_has_username();
  if (username_ == &::google::protobuf::internal::kEmptyString) {
    username_ = new ::std::string;
  }
  return username_;
}
inline ::std::string* BINQuickPlayResponse::release_username() {
  clear_has_username();
  if (username_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = username_;
    username_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void BINQuickPlayResponse::set_allocated_username(::std::string* username) {
  if (username_ != &::google::protobuf::internal::kEmptyString) {
    delete username_;
  }
  if (username) {
    set_has_username();
    username_ = username;
  } else {
    clear_has_username();
    username_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// optional int64 cash = 5;
inline bool BINQuickPlayResponse::has_cash() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void BINQuickPlayResponse::set_has_cash() {
  _has_bits_[0] |= 0x00000010u;
}
inline void BINQuickPlayResponse::clear_has_cash() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void BINQuickPlayResponse::clear_cash() {
  cash_ = GOOGLE_LONGLONG(0);
  clear_has_cash();
}
inline ::google::protobuf::int64 BINQuickPlayResponse::cash() const {
  return cash_;
}
inline void BINQuickPlayResponse::set_cash(::google::protobuf::int64 value) {
  set_has_cash();
  cash_ = value;
}

// optional int64 gold = 6;
inline bool BINQuickPlayResponse::has_gold() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void BINQuickPlayResponse::set_has_gold() {
  _has_bits_[0] |= 0x00000020u;
}
inline void BINQuickPlayResponse::clear_has_gold() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void BINQuickPlayResponse::clear_gold() {
  gold_ = GOOGLE_LONGLONG(0);
  clear_has_gold();
}
inline ::google::protobuf::int64 BINQuickPlayResponse::gold() const {
  return gold_;
}
inline void BINQuickPlayResponse::set_gold(::google::protobuf::int64 value) {
  set_has_gold();
  gold_ = value;
}

// optional int32 avatarId = 7;
inline bool BINQuickPlayResponse::has_avatarid() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void BINQuickPlayResponse::set_has_avatarid() {
  _has_bits_[0] |= 0x00000040u;
}
inline void BINQuickPlayResponse::clear_has_avatarid() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void BINQuickPlayResponse::clear_avatarid() {
  avatarid_ = 0;
  clear_has_avatarid();
}
inline ::google::protobuf::int32 BINQuickPlayResponse::avatarid() const {
  return avatarid_;
}
inline void BINQuickPlayResponse::set_avatarid(::google::protobuf::int32 value) {
  set_has_avatarid();
  avatarid_ = value;
}

// optional string avatarPath = 8;
inline bool BINQuickPlayResponse::has_avatarpath() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
inline void BINQuickPlayResponse::set_has_avatarpath() {
  _has_bits_[0] |= 0x00000080u;
}
inline void BINQuickPlayResponse::clear_has_avatarpath() {
  _has_bits_[0] &= ~0x00000080u;
}
inline void BINQuickPlayResponse::clear_avatarpath() {
  if (avatarpath_ != &::google::protobuf::internal::kEmptyString) {
    avatarpath_->clear();
  }
  clear_has_avatarpath();
}
inline const ::std::string& BINQuickPlayResponse::avatarpath() const {
  return *avatarpath_;
}
inline void BINQuickPlayResponse::set_avatarpath(const ::std::string& value) {
  set_has_avatarpath();
  if (avatarpath_ == &::google::protobuf::internal::kEmptyString) {
    avatarpath_ = new ::std::string;
  }
  avatarpath_->assign(value);
}
inline void BINQuickPlayResponse::set_avatarpath(const char* value) {
  set_has_avatarpath();
  if (avatarpath_ == &::google::protobuf::internal::kEmptyString) {
    avatarpath_ = new ::std::string;
  }
  avatarpath_->assign(value);
}
inline void BINQuickPlayResponse::set_avatarpath(const char* value, size_t size) {
  set_has_avatarpath();
  if (avatarpath_ == &::google::protobuf::internal::kEmptyString) {
    avatarpath_ = new ::std::string;
  }
  avatarpath_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* BINQuickPlayResponse::mutable_avatarpath() {
  set_has_avatarpath();
  if (avatarpath_ == &::google::protobuf::internal::kEmptyString) {
    avatarpath_ = new ::std::string;
  }
  return avatarpath_;
}
inline ::std::string* BINQuickPlayResponse::release_avatarpath() {
  clear_has_avatarpath();
  if (avatarpath_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = avatarpath_;
    avatarpath_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void BINQuickPlayResponse::set_allocated_avatarpath(::std::string* avatarpath) {
  if (avatarpath_ != &::google::protobuf::internal::kEmptyString) {
    delete avatarpath_;
  }
  if (avatarpath) {
    set_has_avatarpath();
    avatarpath_ = avatarpath;
  } else {
    clear_has_avatarpath();
    avatarpath_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// optional int32 level = 9;
inline bool BINQuickPlayResponse::has_level() const {
  return (_has_bits_[0] & 0x00000100u) != 0;
}
inline void BINQuickPlayResponse::set_has_level() {
  _has_bits_[0] |= 0x00000100u;
}
inline void BINQuickPlayResponse::clear_has_level() {
  _has_bits_[0] &= ~0x00000100u;
}
inline void BINQuickPlayResponse::clear_level() {
  level_ = 0;
  clear_has_level();
}
inline ::google::protobuf::int32 BINQuickPlayResponse::level() const {
  return level_;
}
inline void BINQuickPlayResponse::set_level(::google::protobuf::int32 value) {
  set_has_level();
  level_ = value;
}

// optional int64 exp = 10;
inline bool BINQuickPlayResponse::has_exp() const {
  return (_has_bits_[0] & 0x00000200u) != 0;
}
inline void BINQuickPlayResponse::set_has_exp() {
  _has_bits_[0] |= 0x00000200u;
}
inline void BINQuickPlayResponse::clear_has_exp() {
  _has_bits_[0] &= ~0x00000200u;
}
inline void BINQuickPlayResponse::clear_exp() {
  exp_ = GOOGLE_LONGLONG(0);
  clear_has_exp();
}
inline ::google::protobuf::int64 BINQuickPlayResponse::exp() const {
  return exp_;
}
inline void BINQuickPlayResponse::set_exp(::google::protobuf::int64 value) {
  set_has_exp();
  exp_ = value;
}

// optional string sessionId = 11;
inline bool BINQuickPlayResponse::has_sessionid() const {
  return (_has_bits_[0] & 0x00000400u) != 0;
}
inline void BINQuickPlayResponse::set_has_sessionid() {
  _has_bits_[0] |= 0x00000400u;
}
inline void BINQuickPlayResponse::clear_has_sessionid() {
  _has_bits_[0] &= ~0x00000400u;
}
inline void BINQuickPlayResponse::clear_sessionid() {
  if (sessionid_ != &::google::protobuf::internal::kEmptyString) {
    sessionid_->clear();
  }
  clear_has_sessionid();
}
inline const ::std::string& BINQuickPlayResponse::sessionid() const {
  return *sessionid_;
}
inline void BINQuickPlayResponse::set_sessionid(const ::std::string& value) {
  set_has_sessionid();
  if (sessionid_ == &::google::protobuf::internal::kEmptyString) {
    sessionid_ = new ::std::string;
  }
  sessionid_->assign(value);
}
inline void BINQuickPlayResponse::set_sessionid(const char* value) {
  set_has_sessionid();
  if (sessionid_ == &::google::protobuf::internal::kEmptyString) {
    sessionid_ = new ::std::string;
  }
  sessionid_->assign(value);
}
inline void BINQuickPlayResponse::set_sessionid(const char* value, size_t size) {
  set_has_sessionid();
  if (sessionid_ == &::google::protobuf::internal::kEmptyString) {
    sessionid_ = new ::std::string;
  }
  sessionid_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* BINQuickPlayResponse::mutable_sessionid() {
  set_has_sessionid();
  if (sessionid_ == &::google::protobuf::internal::kEmptyString) {
    sessionid_ = new ::std::string;
  }
  return sessionid_;
}
inline ::std::string* BINQuickPlayResponse::release_sessionid() {
  clear_has_sessionid();
  if (sessionid_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = sessionid_;
    sessionid_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void BINQuickPlayResponse::set_allocated_sessionid(::std::string* sessionid) {
  if (sessionid_ != &::google::protobuf::internal::kEmptyString) {
    delete sessionid_;
  }
  if (sessionid) {
    set_has_sessionid();
    sessionid_ = sessionid;
  } else {
    clear_has_sessionid();
    sessionid_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// optional bool enableDebugLag = 12;
inline bool BINQuickPlayResponse::has_enabledebuglag() const {
  return (_has_bits_[0] & 0x00000800u) != 0;
}
inline void BINQuickPlayResponse::set_has_enabledebuglag() {
  _has_bits_[0] |= 0x00000800u;
}
inline void BINQuickPlayResponse::clear_has_enabledebuglag() {
  _has_bits_[0] &= ~0x00000800u;
}
inline void BINQuickPlayResponse::clear_enabledebuglag() {
  enabledebuglag_ = false;
  clear_has_enabledebuglag();
}
inline bool BINQuickPlayResponse::enabledebuglag() const {
  return enabledebuglag_;
}
inline void BINQuickPlayResponse::set_enabledebuglag(bool value) {
  set_has_enabledebuglag();
  enabledebuglag_ = value;
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_quick_5fplay_2eproto__INCLUDED
